name: ci-to-aws

on:
  push:
    branches: ["main", feature/*]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    # TODO (Salvo): Change image
    container: akasomix/aws-lambda-ci-pnpm:latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to AWS
        run: |
          echo "Hello World"

          # TODO (Salvo): Expand process to all lambda folders
