name: ci-to-aws

on:
  push:
    branches: ["main", feature/*]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    container: alpine/terragrunt:1.2.5

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to AWS
        run: |
          STR='GNU/Linux is an operating system'
          SUB='Linux'
          if [[ "$STR" == *"$SUB"* ]]; then
            echo "It's there."
          fi
